### ISSUE TITLE
commands repeat?

### ISSUE THREAD

**Issue by Jaackla** [MineYourMind/BlockCommand#1]
So i'm testing your plugin out and i used one of the examples
/bcmd add <srv> give <player> stone
but i changed it a bit too
/bcmd add <srv> give <player> pixelmon:master_ball 5

it works but it does the command twice so they get 10, even if i use your example it gives 2 stone not to sure why

**Comment by Sir-Will** [comment]
Can you post a screenshot of /bcmd list?

**Comment by Jaackla** [comment]
![image](https://user-images.githubusercontent.com/36846537/43644491-c9322104-9726-11e8-8a94-3267561ce6bc.png)

**Comment by Jaackla** [comment]
![image](https://user-images.githubusercontent.com/36846537/43644501-d58807b6-9726-11e8-9921-2ef7a0ced0ef.png)
this is what it looks like when i click it once

**Comment by Sir-Will** [comment]
Ah, probably the weird sponge issue which triggers the interact event twice. Will look into this soon.

**Comment by Sir-Will** [comment]
@Jaackla Updated to 1.1 and it's fixed.
