### ISSUE TITLE
Cannot use modded blocks

### ISSUE THREAD

**Issue by SirFancyBacon** [MineYourMind/BlockCommand#3]
Hello, log the plugin, but i'd like to report an issue
when attempting to use any block from a Forge Mod the plugin fails to load entirely and commands break.

**Comment by Sir-Will** [comment]
Please post your log and config.

**Comment by SirFancyBacon** [comment]
Sorry for the delay, work has kept be busy!

here is the log:
https://pastebin.com/TjvRy0yM
And here is theconfig:
https://pastebin.com/5YhsMujt

**Comment by Sir-Will** [comment]
Looks like the config is being loaded before the mod registers the blocks.
Please try this version:

[BlockCommand-1.1.jar.zip](https://github.com/MineYourMind/BlockCommand/files/2789949/BlockCommand-1.1.jar.zip)

**Comment by SirFancyBacon** [comment]
That worked!

**Comment by SirFancyBacon** [comment]
How'd you fix that? another plugin i have (itemizer) has the same issue, it loads before Conquest.

**Comment by Sir-Will** [comment]
Moved to config init to a different start event.
